package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.24

import (
	"context"
	"gqlgen-todo/graph/model"
	"strconv"
)

// Todos is the resolver for the todos field.
func (r *queryResolver) Todos(ctx context.Context) ([]*model.Todo, error) {
	todos := []*model.Todo{}
	searched, _ := r.EntClient.Todo.Query().All(ctx)
	for _, todo := range searched {
		todos = append(todos, &model.Todo{
			ID:        strconv.Itoa(todo.ID),
			Title:     todo.Title,
			Note:      todo.Note,
			Completed: todo.Completed,
			CreatedAt: todo.CreatedAt.Format("2006-01-02 15:04:05"),
			UpdatedAt: todo.UpdatedAt.Format("2006-01-02 15:04:05"),
		})
	}
	return todos, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
