version: '3.7'
services:
  db:
    build:
      context: .
      dockerfile: ./dockerfile/db.dockerfile
    container_name: rails_mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      TZ: 'Asia/Tokyo'
    volumes:
      - ./mysql:/var/lib/mysql
      - ./mysql-confd/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./mysql-confd/charset.cnf:/etc/mysql/conf.d/charset.cnf

  web:
    build:
      context: .
      dockerfile: ./dockerfile/web.dockerfile
    container_name: rails_web
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      BINDING: 0.0.0.0
    stdin_open: true
    tty: true
    links:
      - db
