// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Node interface {
	IsNode()
	GetID() string
}

type NewTodo struct {
	ID        *string `json:"id"`
	Title     string  `json:"title"`
	Note      string  `json:"note"`
	Completed *bool   `json:"completed"`
	CreatedAt *string `json:"created_at"`
	UpdatedAt *string `json:"updated_at"`
}

type Todo struct {
	ID        string `json:"id"`
	Title     string `json:"title"`
	Note      string `json:"note"`
	Completed bool   `json:"completed"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

func (Todo) IsNode()            {}
func (this Todo) GetID() string { return this.ID }
