// Code generated by entc, DO NOT EDIT.

package ent

import (
	"echo-ent-crud/ent/schema"
	"echo-ent-crud/ent/todo"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	todoFields := schema.Todo{}.Fields()
	_ = todoFields
	// todoDescName is the schema descriptor for name field.
	todoDescName := todoFields[0].Descriptor()
	// todo.DefaultName holds the default value on creation for the name field.
	todo.DefaultName = todoDescName.Default.(string)
	// todoDescStatus is the schema descriptor for status field.
	todoDescStatus := todoFields[1].Descriptor()
	// todo.DefaultStatus holds the default value on creation for the status field.
	todo.DefaultStatus = todoDescStatus.Default.(bool)
	// todoDescCreatedAt is the schema descriptor for created_at field.
	todoDescCreatedAt := todoFields[2].Descriptor()
	// todo.DefaultCreatedAt holds the default value on creation for the created_at field.
	todo.DefaultCreatedAt = todoDescCreatedAt.Default.(func() time.Time)
}
