version: '3'
services:
  db:
    build:
      context: .
      dockerfile: ./database/Dockerfile
    restart: always
    environment:
      MYSQL_DATABASE: app
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - ./database/mysql:/var/lib/mysql
      - ./database/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./database/initdb.d:/docker-entrypoint-initdb.d
  # app:
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfile
  #   tty: true
  #   volumes:
  #     - ./:/app
  #   ports:
  #     - 8080:8080
  #   depends_on:
  #     - db
  #   command: go run main.go
