FROM alpine:alpine
# MAINTAINER <name>
WORKDIR /root
RUN set -x && \
  apk add --no-cache fish && \
  apk add --no-cache curl && \
  apk add --no-cache git && \
  apk add --no-cache git && \
  curl -L https://get.oh-my.fish
# ADD <src>
# COPY <src>
# USER <name>
# ENV <key> <value>
